name: cd

on:
  push:
    branches:
      - "no-auto-trigger"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{}' \
          ${{ secrets.RENDER_DEPLOY_HOOK }}